export const tags = [
  { label: "Agriculture", value: "Agriculture" },
  { label: "DBT", value: "DBT" },
  { label: "Farmer", value: "Farmer" },
  { label: "Financial Assistance", value: "Financial Assistance" },
  { label: "Seeds", value: "Seeds" },
  { label: "Animal Husbandry", value: "Animal Husbandry" },
  { label: "Cattle Farming", value: "Cattle Farming" },
  { label: "Loan", value: "Loan" },
  { label: "Subsidy", value: "Subsidy" },
  { label: "Improve Economic Conditions", value: "Improve Economic Conditions" },
  { label: "Animal", value: "Animal" },
  { label: "Disease", value: "Disease" },
  { label: "Insurance", value: "Insurance" },
  { label: "Premium", value: "Premium" },
  { label: "Crop Loan", value: "Crop Loan" },
  { label: "Farmers", value: "Farmers" },
  { label: "Zero Interest", value: "Zero Interest" },
  { label: "Award", value: "Award" },
  { label: "Dairy", value: "Dairy" },
  { label: "Farming", value: "Farming" },
  { label: "Husbandry", value: "Husbandry" },
  { label: "Milk", value: "Milk" },
  { label: "Hi-Tech", value: "Hi-Tech" },
  { label: "Milch Animal", value: "Milch Animal" },
  { label: "Mini Dairy Unit", value: "Mini Dairy Unit" },
  { label: "Horticulture", value: "Horticulture" },
  { label: "Strawberry Cultivation", value: "Strawberry Cultivation" },
  { label: "Animal Health", value: "Animal Health" },
  { label: "Livestock Diseases", value: "Livestock Diseases" },
  { label: "Demonstration", value: "Demonstration" },
  { label: "Millets", value: "Millets" },
  { label: "Nutri Cereals", value: "Nutri Cereals" },
  { label: "Pulses", value: "Pulses" },
  { label: "Rice", value: "Rice" },
  { label: "Seed Distribution", value: "Seed Distribution" },
  { label: "Seed Hub", value: "Seed Hub" },
  { label: "Seed Production", value: "Seed Production" },
  { label: "Wheat", value: "Wheat" },
  { label: "Financial", value: "Financial" },
  { label: "Insurance Coverage", value: "Insurance Coverage" },
  { label: "LIC", value: "LIC" },
  { label: "Security", value: "Security" },
  { label: "Playground", value: "Playground" },
  { label: "Recreation", value: "Recreation" },
  { label: "Sports", value: "Sports" },
  { label: "Urban", value: "Urban" },
  { label: "Agricultural Inputs", value: "Agricultural Inputs" },
  { label: "Income Support", value: "Income Support" },
  { label: "Kisan", value: "Kisan" },
  { label: "Seed Supply", value: "Seed Supply" },
  { label: "Tea Development", value: "Tea Development" },
  { label: "Coconut", value: "Coconut" },
  { label: "Garden", value: "Garden" },
  { label: "Plant", value: "Plant" },
  { label: "Seed", value: "Seed" },
  { label: "Cooperative Society", value: "Cooperative Society" },
  { label: "FIG", value: "FIG" },
  { label: "FPC", value: "FPC" },
  { label: "FPO", value: "FPO" },
  { label: "Harvesting Tools", value: "Harvesting Tools" },
  { label: "HRT-3", value: "HRT-3" },
  { label: "Scheduled Tribes", value: "Scheduled Tribes" },
  { label: "SHG", value: "SHG" },
  { label: "Employment", value: "Employment" },
  { label: "Goat Unit", value: "Goat Unit" },
  { label: "Livestock Unit", value: "Livestock Unit" },
  { label: "Milch Animals", value: "Milch Animals" },
  { label: "Piggery Unit", value: "Piggery Unit" },
  { label: "Scheduled Caste", value: "Scheduled Caste" },
  { label: "Self-employment", value: "Self-employment" },
  { label: "Sheep Unit", value: "Sheep Unit" },
  { label: "Unemployed", value: "Unemployed" },
  { label: "Farming Assistance", value: "Farming Assistance" },
  { label: "Pulses Production", value: "Pulses Production" },
  { label: "Training", value: "Training" },
  { label: "Crop Insurance", value: "Crop Insurance" },
  { label: "Crops Damage", value: "Crops Damage" },
  { label: "Bank Account Holders", value: "Bank Account Holders" },
  { label: "Pension", value: "Pension" },
  { label: "Unorganized Workers", value: "Unorganized Workers" },
  { label: "Aquaculture", value: "Aquaculture" },
  { label: "Equipment", value: "Equipment" },
  { label: "Fish", value: "Fish" },
  { label: "Fishermen", value: "Fishermen" },
  { label: "Shrimp", value: "Shrimp" },
  { label: "Business", value: "Business" },
  { label: "Flower Vendors", value: "Flower Vendors" },
  { label: "Fruit Vendors", value: "Fruit Vendors" },
  { label: "Micro Credit Loan", value: "Micro Credit Loan" },
  { label: "Vegetable Vendors", value: "Vegetable Vendors" },
  { label: "Women", value: "Women" },
  { label: "Makhana Development", value: "Makhana Development" },
  { label: "Empower", value: "Empower" },
  { label: "Old Age", value: "Old Age" },
  { label: "Four-wheeler", value: "Four-wheeler" },
  { label: "Marketing", value: "Marketing" },
  { label: "Labour", value: "Labour" },
  { label: "Senior Citizen", value: "Senior Citizen" },
  { label: "Boat", value: "Boat" },
  { label: "Fisherman", value: "Fisherman" },
  { label: "Marine", value: "Marine" },
  { label: "Irrigation", value: "Irrigation" },
  { label: "Pipes", value: "Pipes" },
  { label: "Pulses ISPOM", value: "Pulses ISPOM" },
  { label: "Disease-free Life", value: "Disease-free Life" },
  { label: "Health", value: "Health" },
  { label: "Planting", value: "Planting" },
  { label: "Climate Resilience", value: "Climate Resilience" },
  { label: "Drought", value: "Drought" },
  { label: "NDKSP", value: "NDKSP" },
  { label: "POCRA", value: "POCRA" },
  { label: "Water Conservation", value: "Water Conservation" },
  { label: "Laboratory", value: "Laboratory" },
  { label: "Pesticides", value: "Pesticides" },
  { label: "Testing", value: "Testing" },
  { label: "Trichoderma", value: "Trichoderma" },
  { label: "Trichogramma", value: "Trichogramma" },
  { label: "Development", value: "Development" },
  { label: "Fisheries", value: "Fisheries" },
  { label: "Goat Breeding", value: "Goat Breeding" },
  { label: "Rural Development", value: "Rural Development" },
  { label: "Gypsum", value: "Gypsum" },
  { label: "Oil Seeds", value: "Oil Seeds" },
  { label: "Livestock", value: "Livestock" },
  { label: "Poultry", value: "Poultry" },
  { label: "Rural", value: "Rural" },
  { label: "Fish Farmer", value: "Fish Farmer" },
  { label: "Scheduled Castes", value: "Scheduled Castes" },
  { label: "Broiler Birds", value: "Broiler Birds" },
  { label: "Poultry Farming", value: "Poultry Farming" },
  { label: "Umbrella Scheme", value: "Umbrella Scheme" },
  { label: "Renewable Energy", value: "Renewable Energy" },
  { label: "Solar Irrigation Pumps", value: "Solar Irrigation Pumps" },
  { label: "Kisan Credit Card", value: "Kisan Credit Card" },
  { label: "Contract Farming", value: "Contract Farming" },
  { label: "Research Stations Visit", value: "Research Stations Visit" },
  { label: "Market", value: "Market" },
  { label: "National", value: "National" },
  { label: "Atal", value: "Atal" },
  { label: "Employee", value: "Employee" },
  { label: "Insured Person", value: "Insured Person" },
  { label: "Unemployment", value: "Unemployment" },
  { label: "Pump Installation", value: "Pump Installation" },
  { label: "Micro-Finance", value: "Micro-Finance" },
  { label: "Women Enterpreneur", value: "Women Enterpreneur" },
  { label: "Construction", value: "Construction" },
  { label: "Housing", value: "Housing" },
  { label: "Repair Extension", value: "Repair Extension" },
  { label: "Banana Development", value: "Banana Development" },
  { label: "Plant Supply", value: "Plant Supply" },
  { label: "Disability", value: "Disability" },
  { label: "Education Loan", value: "Education Loan" },
  { label: "PwD", value: "PwD" },
  { label: "Grant", value: "Grant" },
  { label: "Society", value: "Society" },
  { label: "Entrepreneurship", value: "Entrepreneurship" },
  { label: "Scheduled Tribe", value: "Scheduled Tribe" },
  { label: "Engine", value: "Engine" },
  { label: "Maschyajibi", value: "Maschyajibi" },
  { label: "Net", value: "Net" },
  { label: "Agriculture Department", value: "Agriculture Department" },
  { label: "Mukhayamantri", value: "Mukhayamantri" },
  { label: "Saur Swarojgar", value: "Saur Swarojgar" },
  { label: "Fish Production", value: "Fish Production" },
  { label: "Beekeeper", value: "Beekeeper" },
  { label: "Entrepreneurs", value: "Entrepreneurs" },
  { label: "Honey FPO", value: "Honey FPO" },
  { label: "Start Up", value: "Start Up" },
  { label: "Coconut Development", value: "Coconut Development" },
  { label: "Crop Display", value: "Crop Display" },
  { label: "Financial Support", value: "Financial Support" },
  { label: "Education", value: "Education" },
  { label: "Public School", value: "Public School" },
  { label: "Vidya Niketan", value: "Vidya Niketan" },
  { label: "Vimukta Jatis And Nomadic Tribes", value: "Vimukta Jatis And Nomadic Tribes" },
  { label: "Farmer Group", value: "Farmer Group" },
  { label: "General Category", value: "General Category" },
  { label: "HRT-2", value: "HRT-2" },
  { label: "Post-Harvest Management", value: "Post-Harvest Management" },
  { label: "Shorting Equipment", value: "Shorting Equipment" },
  { label: "Tools", value: "Tools" },
  { label: "Agriculture And Rural Development Bank", value: "Agriculture And Rural Development Bank" },
  { label: "Irrigated Area", value: "Irrigated Area" },
  { label: "Sericulture", value: "Sericulture" },
  { label: "Bio-Floc", value: "Bio-Floc" },
  { label: "Odisha", value: "Odisha" },
  { label: "Livestock Rearing", value: "Livestock Rearing" },
  { label: "Malnutrition", value: "Malnutrition" },
  { label: "Vegetable Cultivation", value: "Vegetable Cultivation" },
  { label: "Road", value: "Road" },
  { label: "Cattle Herders", value: "Cattle Herders" },
  { label: "Cow Protection", value: "Cow Protection" },
  { label: "New Employment", value: "New Employment" },
  { label: "Organic Fertilizers", value: "Organic Fertilizers" },
  { label: "Foundation Seeds", value: "Foundation Seeds" },
  { label: "Crop", value: "Crop" },
  { label: "Income Generation Opportunities", value: "Income Generation Opportunities" },
  { label: "Sheep Breeders", value: "Sheep Breeders" },
  { label: "Sheep Farming", value: "Sheep Farming" },
  { label: "Subsidized Rams", value: "Subsidized Rams" },
  { label: "Transport", value: "Transport" },
  { label: "Orchard", value: "Orchard" },
  { label: "Development Of Green Estate", value: "Development Of Green Estate" },
  { label: "Environment Infrastructure", value: "Environment Infrastructure" },
  { label: "Integrated Development", value: "Integrated Development" },
  { label: "Mission", value: "Mission" },
  { label: "North Eastern Hill", value: "North Eastern Hill" },
  { label: "Cultivation", value: "Cultivation" },
  { label: "Fodder", value: "Fodder" },
  { label: "Direct Benefit Transfer", value: "Direct Benefit Transfer" },
  { label: "General", value: "General" },
  { label: "Plantation", value: "Plantation" },
  { label: "Shednet House", value: "Shednet House" },
  { label: "Honour", value: "Honour" },
  { label: "Research", value: "Research" },
  { label: "Rhizobium", value: "Rhizobium" },
  { label: "Bio-pesticide", value: "Bio-pesticide" },
  { label: "IPM", value: "IPM" },
  { label: "Organic Crop", value: "Organic Crop" },
  { label: "Pest Management", value: "Pest Management" },
  { label: "Plant Protection", value: "Plant Protection" },
  { label: "Divyang", value: "Divyang" },
  { label: "Rhode Island Red (RIR)", value: "Rhode Island Red (RIR)" },
  { label: "Mechanization", value: "Mechanization" },
  { label: "Cash Assistance", value: "Cash Assistance" },
  { label: "Schedule Caste", value: "Schedule Caste" },
  { label: "Stipend", value: "Stipend" },
  { label: "Agriculture Management System", value: "Agriculture Management System" },
  { label: "Integrated Technology", value: "Integrated Technology" },
  { label: "ITEAMS", value: "ITEAMS" },
  { label: "Telephone Advice", value: "Telephone Advice" },
  { label: "StartUp", value: "StartUp" },
  { label: "Youth", value: "Youth" },
  { label: "Coffee", value: "Coffee" },
  { label: "Water", value: "Water" },
  { label: "Maize", value: "Maize" },
  { label: "Farm", value: "Farm" },
  { label: "Land", value: "Land" },
  { label: "Crops", value: "Crops" },
  { label: "Walk In Tunnel", value: "Walk In Tunnel" },
  { label: "Student", value: "Student" },
  { label: "Vegetables", value: "Vegetables" },
  { label: "Female", value: "Female" },
  { label: "Household", value: "Household" },
  { label: "Accident", value: "Accident" },
  { label: "Journalist", value: "Journalist" },
  { label: "Media", value: "Media" },
  { label: "Mediclaim", value: "Mediclaim" },
  { label: "Krishi", value: "Krishi" },
  { label: "KUY", value: "KUY" },
  { label: "MOVCDNER", value: "MOVCDNER" },
  { label: "Unnati", value: "Unnati" },
  { label: "Chaff Cutter", value: "Chaff Cutter" },
  { label: "Dairy Farming", value: "Dairy Farming" },
  { label: "TASP", value: "TASP" },
  { label: "Electrical", value: "Electrical" },
  { label: "Power Subsidy", value: "Power Subsidy" },
  { label: "Scheduled Tribe Farmers", value: "Scheduled Tribe Farmers" },
  { label: "Large Ruminants", value: "Large Ruminants" },
  { label: "NLM", value: "NLM" },
  { label: "Pashu Kisan Credit Card", value: "Pashu Kisan Credit Card" },
  { label: "Poultry Farming Training", value: "Poultry Farming Training" },
  { label: "Poultry Units", value: "Poultry Units" },
  { label: "Rural Poor", value: "Rural Poor" },
  { label: "SC", value: "SC" },
  { label: "Scheduled Caste Farmers", value: "Scheduled Caste Farmers" },
  { label: "Small Ruminants", value: "Small Ruminants" },
  { label: "Training Programmes", value: "Training Programmes" },
  { label: "Agricultural Inputs Distribution", value: "Agricultural Inputs Distribution" },
  { label: "Antyodaya Anna Yojana", value: "Antyodaya Anna Yojana" },
  { label: "AAY", value: "AAY" },
  { label: "Below Poverty Line", value: "Below Poverty Line" },
  { label: "BPL", value: "BPL" },
  { label: "Food Grains", value: "Food Grains" },
  { label: "Ration Card", value: "Ration Card" },
  { label: "Rural Families", value: "Rural Families" },
  { label: "State", value: "State" },
  { label: "Wheat Based Ration", value: "Wheat Based Ration" },
  { label: "Work Participation", value: "Work Participation" },
  { label: "LPG", value: "LPG" },
  { label: "Pradhan Mantri Ujjwala Yojana", value: "Pradhan Mantri Ujjwala Yojana" },
  { label: "Cooking Gas", value: "Cooking Gas" },
  { label: "Women Empowerment", value: "Women Empowerment" },
  { label: "Organic Farming", value: "Organic Farming" },
  { label: "Organic Manure", value: "Organic Manure" },
  { label: "Technology", value: "Technology" },
  { label: "Charcoal Gasifier", value: "Charcoal Gasifier" },
  { label: "Soft Loan", value: "Soft Loan" },
  { label: "Biogas", value: "Biogas" },
  { label: "Vermi Compost", value: "Vermi Compost" },
  { label: "Organic Farming Certification", value: "Organic Farming Certification" },
  { label: "Chemical Fertilizers", value: "Chemical Fertilizers" },
  { label: "Natural Fertilizers", value: "Natural Fertilizers" },
  { label: "Gobar Gas", value: "Gobar Gas" },
  { label: "Rural Youth", value: "Rural Youth" },
  { label: "Cattle Farmers", value: "Cattle Farmers" }
];
